### ISSUE TITLE
Error in parsing WITH for bucketing in Trino

### ISSUE THREAD

**Issue by chezou** [reata/sqllineage#251]
When trying to parse bucketing query in Trino, WITH clause is treated as CTE so that parse fails.

Example query from Trino blog (https://trino.io/blog/2019/05/29/improved-hive-bucketing.html):

```sql
CREATE TABLE page_views (
  user_id bigint,
  page_url varchar,
  dt date
)
WITH (
  partitioned_by = ARRAY['dt'],
  bucketed_by = ARRAY['user_id'],
  bucket_count = 50
)

```

Actual error with sqllineage.

```sh
$ .venv/bin/sqllineage -e "CREATE TABLE tbl1 (col1 VARCHAR) WITH (bucketed_by = array['col1'], bucket_count = 256);"
Traceback (most recent call last):
  File "/Users/ariga/src/td-misc/aki/lineage/.venv/bin/sqllineage", line 8, in <module>
    sys.exit(main())
  File "/Users/ariga/src/td-misc/aki/lineage/.venv/lib/python3.10/site-packages/sqllineage/cli.py", line 82, in main
    runner.print_table_lineage()
  File "/Users/ariga/src/td-misc/aki/lineage/.venv/lib/python3.10/site-packages/sqllineage/runner.py", line 166, in print_table_lineage
    print(str(self))
  File "/Users/ariga/src/td-misc/aki/lineage/.venv/lib/python3.10/site-packages/sqllineage/runner.py", line 22, in wrapper
    self._eval()
  File "/Users/ariga/src/td-misc/aki/lineage/.venv/lib/python3.10/site-packages/sqllineage/runner.py", line 179, in _eval
    self._stmt_holders = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
  File "/Users/ariga/src/td-misc/aki/lineage/.venv/lib/python3.10/site-packages/sqllineage/runner.py", line 179, in <listcomp>
    self._stmt_holders = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
  File "/Users/ariga/src/td-misc/aki/lineage/.venv/lib/python3.10/site-packages/sqllineage/core/analyzer.py", line 54, in analyze
    self._extract_from_dml(stmt, AnalyzerContext())
  File "/Users/ariga/src/td-misc/aki/lineage/.venv/lib/python3.10/site-packages/sqllineage/core/analyzer.py", line 116, in _extract_from_dml
    next_handler.handle(sub_token, holder)
  File "/Users/ariga/src/td-misc/aki/lineage/.venv/lib/python3.10/site-packages/sqllineage/core/handlers/base.py", line 39, in handle
    self._handle(token, holder)
  File "/Users/ariga/src/td-misc/aki/lineage/.venv/lib/python3.10/site-packages/sqllineage/core/handlers/cte.py", line 27, in _handle
    raise SQLLineageException(
sqllineage.exceptions.SQLLineageException: An Identifier or IdentifierList is expected, got Parenthesis[value: (bucketed_by = array['col1'], bucket_count = 256)] instead.
```

It is because trying to find Identifier by assuming WITH clause is CTE.

**Comment by reata** [comment]
This is something we can do better, I just saw your PR, we can continue our discussion there.
