### ISSUE TITLE
SQLLineageException when CREATE VIEW defined as SELECT ... FROM ( VALUES ... )

### ISSUE THREAD

**Issue by dvasdekis** [reata/sqllineage#292]
Similar to #290 , when a CREATE VIEW statement is defined as either example present in the below:

```sql
CREATE OR ALTER VIEW tbl1 AS
    SELECT  cast(my_overrides.col1 as varchar(100)) as col1
   , cast(my_overrides.col2 as varchar(100)) as col2
   , cast(my_overrides.col3 as datetime2) as col3
   , cast(my_overrides.col4 as datetime2) as col4
   , cast(my_overrides.col5 as smallint) as col5
   , cast(my_overrides.col6 as varchar(1024)) as col6
    FROM  (VALUES
     ('data','thing1','1971-01-01 00:00:00', '1971-01-01 00:00:10', '91', 'some text')
   , ('data','thing2','1971-01-01 00:00:10', '1971-01-01 00:00:20', '92', 'some text')
   , ('data','thing3','1971-01-01 00:00:10', '1971-01-01 00:00:20', '92', 'some text')   
 )my_overrides(col1, col2, col3, col4, col5, col6) ;

-- same result but with inferred column names and types
CREATE OR ALTER VIEW tbl2 AS
    SELECT * FROM  (VALUES
     ('data','thing1','1971-01-01 00:00:00', '1971-01-01 00:00:10', '91', 'some text')
   , ('data','thing2','1971-01-01 00:00:10', '1971-01-01 00:00:20', '92', 'some text')
   , ('data','thing3','1971-01-01 00:00:10', '1971-01-01 00:00:20', '92', 'some text')
 )my_overrides(col1, col2, col3, col4, col5, col6) ;
```

The result is 
```bash
PS C:\proj> sqllineage -f '.\try.sql'
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\sqllineage.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\sqllineage\cli.py", line 86, in main
    runner.print_table_lineage()
  File "C:\Python310\lib\site-packages\sqllineage\runner.py", line 166, in print_table_lineage
    print(str(self))
  File "C:\Python310\lib\site-packages\sqllineage\runner.py", line 22, in wrapper
    self._eval()
  File "C:\Python310\lib\site-packages\sqllineage\runner.py", line 179, in _eval
    self._stmt_holders = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
  File "C:\Python310\lib\site-packages\sqllineage\runner.py", line 179, in <listcomp>
    self._stmt_holders = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
  File "C:\Python310\lib\site-packages\sqllineage\core\analyzer.py", line 60, in analyze
    self._extract_from_dml(stmt, AnalyzerContext())
  File "C:\Python310\lib\site-packages\sqllineage\core\analyzer.py", line 135, in _extract_from_dml
    next_handler.handle(sub_token, holder)
  File "C:\Python310\lib\site-packages\sqllineage\core\handlers\base.py", line 39, in handle
    self._handle(token, holder)
  File "C:\Python310\lib\site-packages\sqllineage\core\handlers\source.py", line 56, in _handle
    self._handle_table(token, holder)
  File "C:\Python310\lib\site-packages\sqllineage\core\handlers\source.py", line 74, in _handle_table
    self._handle(token.tokens[1], holder)
  File "C:\Python310\lib\site-packages\sqllineage\core\handlers\source.py", line 56, in _handle
    self._handle_table(token, holder)
  File "C:\Python310\lib\site-packages\sqllineage\core\handlers\source.py", line 78, in _handle_table
    raise SQLLineageException(
sqllineage.exceptions.SQLLineageException: An Identifier is expected, got Token[value: VALUES] instead.
```

I hope it's OK to treat it in a similar way to #291 as this is what seems to be the right approach (just ignore it)? Is there any information of value that you would like to scrap from the VALUES statement? (e.g. column-based lineage?). I'll assume not for now, but please let me know if so.

Thanks again!

**Comment by reata** [comment]
Thank you. I don't think we need any information for VALUES statement as well. We can just make a exemption rule to make sure the exception goes away.
