### ISSUE TITLE
SQLLineageException when sourcing view from UNNEST() (Athena)

### ISSUE THREAD

**Issue by alfredo-f** [reata/sqllineage#301]
First and foremost, this package is awesome! 😄

Issue similar to #290 

[Presto syntax to expand arrays](https://prestodb.io/docs/current/sql/select.html#unnest)

```sql
SELECT *
FROM
    _table s
    CROSS JOIN
    UNNEST(s.column_1) t(column_1)
```

Error

```shell
PS C:> sqllineage -f "above_file.sql"
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\sqllineage.exe\__main__.py", line 7, in <module>
  File "c:\Python38\lib\site-packages\sqllineage\cli.py", line 86, in main
    runner.print_table_lineage()
  File "c:\Python38\lib\site-packages\sqllineage\runner.py", line 166, in print_table_lineage
    print(str(self))
  File "c:\Python38\lib\site-packages\sqllineage\runner.py", line 22, in wrapper
    self._eval()
  File "c:\Python38\lib\site-packages\sqllineage\runner.py", line 179, in _eval
    self._stmt_holders = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
  File "c:\Python38\lib\site-packages\sqllineage\runner.py", line 179, in <listcomp>
    self._stmt_holders = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
  File "c:\Python38\lib\site-packages\sqllineage\core\analyzer.py", line 60, in analyze
    self._extract_from_dml(stmt, AnalyzerContext())
  File "c:\Python38\lib\site-packages\sqllineage\core\analyzer.py", line 135, in _extract_from_dml
    next_handler.handle(sub_token, holder)
  File "c:\Python38\lib\site-packages\sqllineage\core\handlers\base.py", line 39, in handle
    self._handle(token, holder)
  File "c:\Python38\lib\site-packages\sqllineage\core\handlers\source.py", line 56, in _handle
    self._handle_table(token, holder)
  File "c:\Python38\lib\site-packages\sqllineage\core\handlers\source.py", line 78, in _handle_table
    raise SQLLineageException(
sqllineage.exceptions.SQLLineageException: An Identifier is expected, got Function[value: UNNEST(s.column_1)] instead.
```

**Comment by reata** [comment]
UNNEST is new to me, thanks for the document link. In this case, we can just ignore the UNNEST function call and give back _table as source table. That should solve your problem, correct?

**Comment by alfredo-f** [comment]
Looks like a workaround is adhering to the official example and explicitly using `AS`

```sql
SELECT *
FROM
    _table s
    CROSS JOIN
    UNNEST(s.column_1) AS t (column_1)
```

No errors

```shell
PS C:> sqllineage -f "above_file.sql"
Statements(#): 1
Source Tables:
    <default>._table
    <default>.unnest
Target Tables:

```

but I'm afraid `column_1` wouldn't be considered in column lineage. What do you think?

**Comment by reata** [comment]
Oh, column lineage is another problem. Actually we don't handle any column lineage in a non select context. It would be the same as column in where or group by, we simply just ignore it. Let's make the table lineage work first.

**Comment by reata** [comment]
With #307 merged, select from UNNEST functions won't throw a exception any more. I'll leave this issue open for column lineage reference. Now for sql:

```sql
SELECT student, score FROM tests CROSS JOIN UNNEST(scores) AS t (score)
```

We still parse student, score as columns accessed, instead of student, scores.

**Comment by KulykDmytro** [comment]
issue is resolved in 1.3.7 (as i can see)
in case you use following syntax (Athena v2 syntax which is Presto underneath)
```sql
SELECT
    r.transaction_id,
    i.item_name,
    i.value
FROM raw.ph2_sophia_request AS r
CROSS JOIN UNNEST(r.execution_items) AS i(item_name, value)
WHERE r.transaction_type = 'Payout'
    AND r.dt > DATE '2022-09-01'
```

**Comment by KulykDmytro** [comment]
however adding space after `UNNEST` causing slightly different results
```bash
Statement #1: SELECT    r.transaction_id,    i.item_name,    i.v...
    table read: [Table: <default>.i, Table: raw.ph2_sophia_request]
    table write: []
    table cte: []
    table drop: []
    table rename: []
==========
Summary:
Statements(#): 1
Source Tables:
    <default>.i
    raw.ph2_sophia_request
Target Tables:
```

**Comment by reata** [comment]
@KulykDmytro thanks for reporting this. Adding a space subtly changed the AST generated by sqlparse.

`UNNEST(r.execution_items) AS i(item_name, value)` is parsed as IDENTIFIER(FUNCTION + AS + FUNCTION), while `UNNEST 
 (r.execution_items) AS  i(item_name, value)`  is parsed as KEYWORD + IDENTIFIER. 

This is the situation we have to face with sqlparse. And some other seemingly unrelated code (logic handling CREATE TABLE IF NOT EXISTS) has to be updated at the same time. 

With #309 merged, it's now fixed in master branch. This case also proves the necessity of #302 in demonstrating how unrelated features can impact each other because of the non-validating parsing.

**Comment by reata** [comment]
Re-purposing this issue to column level lineage for UNNEST function call in Presto.
