### ISSUE TITLE
Support "UTF-8" or other 

### ISSUE THREAD

**Issue by Light-Towers** [reata/sqllineage#482]
**Describe the bug**
* All of my SQL files,  encoding set is "UTF-8" .  Can it be supported   "UTF-8" or other  encoding set ?  Thanks 

**SQL**
```sql
insert into analyze select * from foo;
```

**To Reproduce**
```shell
sqllineage -f D:\code\warehouse\hive\hsql\dim\test.sql
```
```
Traceback (most recent call last):
  File "D:\Program Files\miniconda3\envs\py310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\miniconda3\envs\py310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\miniconda3\envs\py310\Scripts\sqllineage.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Program Files\miniconda3\envs\py310\lib\site-packages\sqllineage\cli.py", line 93, in main
    sql = extract_sql_from_args(args)
  File "D:\Program Files\miniconda3\envs\py310\lib\site-packages\sqllineage\utils\helpers.py", line 17, in extract_sql_from_args
    sql = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8e in position 5: illegal multibyte sequence
```

**Python version (available via `python --version`)**
 - 3.10.11

**SQLLineage version (available via `sqllineage --version`):**
 - 1.4.8

**Comment by reata** [comment]
The encoding used by Python's builtin open function is platform dependent, which you can verify with following command:
```shell
python -c "import locale; print(locale.getpreferredencoding(False))"
```
And it should return 'gbk' in your machine. Use gbk to read a utf-8 encoding file caused the exception.


Right now we don't provide an encoding option for user to choose. As a short-term solution, you can enable Python UTF-8 Mode via environment variable [PYTHONUTF8](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUTF8).
